name: OraxenUIFilter
main: me.apatuka.OraxenUIFilter.OraxenUIFilter
version: 1.1
api-version: '1.13'
author: [ apatuka ]
depend: [MythicLib,MMOItems]
softdepend: [Oraxen,ItemsAdder]
commands:
  uimanager:
    permission: oraxenuifilter.access
    description: UIFilter
    aliases: []